name: timetable
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: user
      POSTGRES_DB: timetable
    ports:
      - 5433:5432
  app:
    restart: always
    build:
      .
    environment:
      - POSTGRES_DB_HOST=db
    ports:
      - 8337:8080


